### ISSUE TITLE
Support plux build system

### ISSUE THREAD

**Issue by alexandru0-dev** [pyproject-nix/build-system-pkgs#3]
Plux is needed for building localstack (why not using the nixpkgs? mainly because the optional dependencies are not implemented. also upstream doesn't respect version constraints)

It's already packaged in nixpkgs:
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=plux

https://github.com/localstack/plux?tab=readme-ov-file#configuring-your-distribution

**Comment by adisbladis** [comment]
Added in 5f38d53e9359e9e191ecbc3b8eb068bf613c713c.
